"""Add influx fields to tenant

Revision ID: 17e75b238df4
Revises: 50bb3eb88298
Create Date: 2026-03-30 15:42:42.672790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e75b238df4'
down_revision: Union[str, None] = '50bb3eb88298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('influx_bucket', sa.String(length=255), nullable=True))
    op.add_column('tenant', sa.Column('influx_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'influx_token')
    op.drop_column('tenant', 'influx_bucket')
    # ### end Alembic commands ###
