"""Add influx_token to device

Revision ID: e06013ff8435
Revises: 17e75b238df4
Create Date: 2026-03-30 16:04:12.202232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06013ff8435'
down_revision: Union[str, None] = '17e75b238df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('influx_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'influx_token')
    # ### end Alembic commands ###
